#!/bin/sh
echo "Configure and deploy"
set +e
npm install .
COFFEE="./node_modules/coffee-script/bin/coffee"
$COFFEE -c -o ./public/javascripts ./assets/javascripts/*.coffee
$COFFEE -c ./settings.coffee
$COFFEE patch.coffee ./settings.js ./public/javascripts/inject.js https://encipher.it
