#!/bin/bash
HOME=$(cd `dirname $0` && pwd)
DAEMON=encipher.js
USER=encipher
GROUP=encipher
NODE=$(which node)

export NODE_PATH=/usr/local/lib/node_modules/

case "$1" in
  start)
    echo "Starting $DAEMON (home: $HOME)"
    # Activate the virtual environment
    # Run start-stop-daemon, the $DAEMON variable contains the path to the
    # application to run
    start-stop-daemon --start \
        --background \
	--make-pidfile \
        --pidfile /tmp/$DAEMON.pid \
        --chdir $HOME \
        --user  $USER \
        --group $GROUP \
        --chuid $USER \
        --exec $NODE -- $HOME/$DAEMON
    ;;
  stop)
    echo "Stopping $DAEMON"
    start-stop-daemon --stop --pidfile /tmp/$DAEMON.pid --verbose
    ;;

  *)
    # Refuse to do other stuff
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
