#!/bin/bash
HOME=$(cd `dirname $0` && pwd)
DAEMON=encipher.coffee
USER=encipher
GROUP=encipher
NODE=/home/cloudpub/cloudpub/bin/node
COFFEE=$HOME/node_modules/coffee-script/bin/coffee
OPTS="--port=3000 --interface=127.0.0.1"

function start {
    echo "Starting $DAEMON (home: $HOME)"
    /sbin/start-stop-daemon --start \
        --background \
	--make-pidfile \
        --pidfile /tmp/multiplay.pid \
        --chdir $HOME \
        --user  $USER \
        --group $GROUP \
        --chuid $USER \
        --exec $NODE -- $COFFEE $HOME/$DAEMON $OPTS
}

function stop {
    echo "Stopping $DAEMON"
    /sbin/start-stop-daemon --stop --pidfile /tmp/multiplay.pid --verbose
}

case "$1" in
  start)
      start
    ;;
  stop)
      stop
    ;;
  restart)
      stop
      start
    ;;
  run)
         $NODE $COFFEE $HOME/$DAEMON $OPTS
    ;;
  console)
         sudo -u $USER -g $GROUP $NODE $HOME/$DAEMON $OPTS
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: $0 {start|stop|restart|console|run}"
    exit 1
    ;;
esac

exit 0
